Actuator now closes the connections after use
bigsea-ufcg/bigsea-scaler pull request #19
Opened 2017-12-07 15:16 UTC by armstrongmsg

This commit fixes the crashes caused by opening multiple connections by the Actuator when accessing compute nodes.

2017-12-11 23:34 UTC, betobetodev requested changes

2017-12-11 23:34 UTC, robertonscjr commented on bigsea-controller/service/api/actuator/plugins/kvm_io_actuator.py
>          authorization = self.authorizer.get_authorization(self.authorization_data['authorization_url'],
Break those giant lines in lines that have a maximum of 79 characters.

2017-12-12 12:47 UTC, igornatanael requested changes
ssh_utils is not being used in kvm_upv plugin, so this problem persists there. Please add the close connections or change it to use ssh_utils. There is another problem in this plugin: the ssh connection is opened before instantiate the plugin and it is used as a parameter to the plugin constructor. 

In the os_generic_metric_source the connections are being opened but not closed as well: https://github.com/bigsea-ufcg/bigsea-controller/blob/2a053c232062c103d67d31406714adb5d2d4debb/bigsea-controller/service/api/controller/plugins/os_generic/os_generic_metric_source.py

2017-12-12 16:41 UTC, betobetodev approved these changes

2017-12-12 17:00 UTC, igornatanael approved these changes

2017-12-12 17:00 UTC, merged